export const SCHEMA = {
  USER: 'users',
  ROLE: 'role',
  ADDRESS: 'address',
  SHIPPER: 'shippers',
  VENDOR: 'vendor',
  CART: 'carts',
  RATE: 'rates',
  ORDER: 'orders',
  PRODUCT: 'products',
  ORDERITEM: 'orderitems',
  PAYMENT: 'payments',
  PROMOTION: 'promotions',
  CATEGORY: 'categories',
  STORE: 'stores',
  VOUCHER: 'vouchers',
};
